/** GameIcon alone resolves these names; all icon files live in public/assets/icons. */
export const iconRegistry: ReadonlyMap<string, string> = new Map([
  ['item-spirit-fruit', '/assets/icons/item-spirit-fruit-ink-v2.webp'],
  ['item-talisman', '/assets/icons/item-talisman-ink-v2.webp'],
  ['item-spirit-seed', '/assets/icons/item-spirit-seed-ink-v2.webp'],
  ['item-manual-jade', '/assets/icons/item-manual-jade-ink-v2.webp'],
  ['item-beast-seal', '/assets/icons/item-beast-seal-ink-v2.webp'],
  ['item-spirit-ore', '/assets/icons/item-spirit-ore-ink-v2.webp'],
  ['item-beast-material', '/assets/icons/item-beast-material-ink-v2.webp'],
  ['item-crafting-aux', '/assets/icons/item-crafting-aux-ink-v2.webp'],
  [
    'item-heavenly-treasure',
    '/assets/icons/item-heavenly-treasure-ink-v2.webp',
  ],
  ['item-origin-dew', '/assets/icons/item-origin-dew-ink-v2.webp'],
  ['equipment-empty-head', '/assets/icons/equipment-empty-head-ink-v1.webp'],
  [
    'equipment-empty-weapon',
    '/assets/icons/equipment-empty-weapon-ink-v1.webp',
  ],
  ['equipment-empty-belt', '/assets/icons/equipment-empty-belt-ink-v1.webp'],
  [
    'equipment-empty-necklace',
    '/assets/icons/equipment-empty-necklace-ink-v1.webp',
  ],
  ['equipment-empty-armor', '/assets/icons/equipment-empty-armor-ink-v1.webp'],
  [
    'equipment-empty-footwear',
    '/assets/icons/equipment-empty-footwear-ink-v1.webp',
  ],
  ['ui-question', '/assets/icons/ui-question-ink-v1.svg'],
  ['ui-crown', '/assets/icons/ui-crown-ink-v1.webp'],
  ['ui-armor', '/assets/icons/ui-armor-ink-v1.webp'],
  ['ui-necklace', '/assets/icons/ui-necklace-ink-v1.webp'],
  ['ui-belt', '/assets/icons/ui-belt-ink-v1.webp'],
  ['ui-boots', '/assets/icons/ui-boots-ink-v1.webp'],
  ['ui-lantern', '/assets/icons/ui-lantern-ink-v1.webp'],
  ['ui-candle', '/assets/icons/ui-candle-ink-v1.webp'],
  ['ui-taiji', '/assets/icons/ui-taiji-ink-v1.webp'],
  ['beast-skill-strength', '/assets/icons/beast-skill-strength-ink-v1.webp'],
  ['beast-skill-stealth', '/assets/icons/beast-skill-stealth-ink-v1.webp'],
  [
    'beast-skill-perception',
    '/assets/icons/beast-skill-perception-ink-v1.webp',
  ],
  ['beast-skill-poison', '/assets/icons/beast-skill-poison-ink-v1.webp'],
  [
    'beast-skill-spirit-flame',
    '/assets/icons/beast-skill-spirit-flame-ink-v1.webp',
  ],
  ['beast-skill-thunder', '/assets/icons/beast-skill-thunder-ink-v1.webp'],
  [
    'beast-skill-falling-rock',
    '/assets/icons/beast-skill-falling-rock-ink-v1.webp',
  ],
  [
    'beast-skill-thunderstorm',
    '/assets/icons/beast-skill-thunderstorm-ink-v1.webp',
  ],
  [
    'beast-skill-mountain-crush',
    '/assets/icons/beast-skill-mountain-crush-ink-v1.webp',
  ],
  ['beast-skill-flood', '/assets/icons/beast-skill-flood-ink-v1.webp'],
  ['ui-spirit-stones', '/assets/icons/ui-spirit-stones-ink-v1.webp'],
  ['ui-scroll', '/assets/icons/ui-scroll-ink-v1.webp'],
  ['ui-manual', '/assets/icons/ui-manual-ink-v1.webp'],
  ['ui-elixir', '/assets/icons/ui-elixir-ink-v1.webp'],
  ['ui-spirit-water', '/assets/icons/ui-spirit-water-ink-v1.webp'],
  ['ui-sword', '/assets/icons/ui-sword-ink-v1.webp'],
  ['ui-treasure-chest', '/assets/icons/ui-treasure-chest-ink-v1.webp'],
  ['ui-spirit-herb', '/assets/icons/ui-spirit-herb-ink-v1.webp'],
  ['ui-merit-medal', '/assets/icons/ui-merit-medal-ink-v1.webp'],
  ['ui-lotus', '/assets/icons/ui-lotus-ink-v1.webp'],
  ['ui-bell', '/assets/icons/ui-bell-ink-v1.webp'],
  ['ui-letter', '/assets/icons/ui-letter-ink-v1.webp'],
  ['ui-compass', '/assets/icons/ui-compass-ink-v1.webp'],
  ['ui-brush', '/assets/icons/ui-brush-ink-v1.webp'],
  ['ui-mirror', '/assets/icons/ui-mirror-ink-v1.webp'],
  ['ui-divination', '/assets/icons/ui-divination-ink-v1.webp'],
  ['ui-mechanism', '/assets/icons/ui-mechanism-ink-v1.webp'],
  ['ui-success', '/assets/icons/ui-success-ink-v1.svg'],
  ['ui-warning', '/assets/icons/ui-warning-ink-v1.svg'],
  ['ui-danger', '/assets/icons/ui-danger-ink-v1.svg'],
  ['beast-fusion-cauldron', '/assets/icons/beast-fusion-cauldron.png'],
  ['earthfire-furnace', '/assets/icons/earthfire-furnace-ink.png'],
  ['xuanfire-furnace', '/assets/icons/xuanfire-furnace-ink.png'],
  ['map-wild', '/assets/icons/map-wild.webp'],
  ['map-dungeon', '/assets/icons/map-dungeon.webp'],
  ['map-market', '/assets/icons/map-market.webp'],
  ['map-sect', '/assets/icons/map-sect.webp'],
  ['map-landmark', '/assets/icons/map-landmark.webp'],

  [
    'beast-skill-all-seeing',
    '/assets/icons/beast-skill-all-seeing-totem-v2.webp',
  ],
  [
    'beast-skill-bloodthirsty-pursuit',
    '/assets/icons/beast-skill-bloodthirsty-pursuit-totem-v2.webp',
  ],
  [
    'beast-skill-surprise-spell',
    '/assets/icons/beast-skill-surprise-spell-totem-v2.webp',
  ],
  [
    'beast-skill-innate-wisdom',
    '/assets/icons/beast-skill-innate-wisdom-totem-v2.webp',
  ],
  [
    'beast-skill-unanticipated',
    '/assets/icons/beast-skill-unanticipated-totem-v2.webp',
  ],
  [
    'beast-skill-overwhelming-might',
    '/assets/icons/beast-skill-overwhelming-might-totem-v2.webp',
  ],
  [
    'beast-skill-spirit-guard',
    '/assets/icons/beast-skill-spirit-guard-totem-v2.webp',
  ],
  [
    'beast-skill-wind-strike',
    '/assets/icons/beast-skill-wind-strike-totem-v2.webp',
  ],
  [
    'beast-skill-barrier-breaker',
    '/assets/icons/beast-skill-barrier-breaker-totem-v2.webp',
  ],
  [
    'beast-skill-mind-shatter',
    '/assets/icons/beast-skill-mind-shatter-totem-v2.webp',
  ],
  [
    'beast-skill-radiant-barrier',
    '/assets/icons/beast-skill-radiant-barrier-totem-v2.webp',
  ],
  [
    'beast-skill-auspicious-vitality',
    '/assets/icons/beast-skill-auspicious-vitality-totem-v2.webp',
  ],
  [
    'beast-skill-spell-reflection',
    '/assets/icons/beast-skill-spell-reflection-totem-v2.webp',
  ],
  [
    'beast-skill-spell-resistance',
    '/assets/icons/beast-skill-spell-resistance-totem-v2.webp',
  ],
  ['beast-skill-miracle', '/assets/icons/beast-skill-miracle-totem-v2.webp'],
  [
    'beast-skill-spell-combo',
    '/assets/icons/beast-skill-spell-combo-totem-v2.webp',
  ],
  ['beast-skill-exorcism', '/assets/icons/beast-skill-exorcism-totem-v2.webp'],
  ['beast-skill-wisdom', '/assets/icons/beast-skill-wisdom-totem-v2.webp'],
  [
    'beast-skill-spell-mastery',
    '/assets/icons/beast-skill-spell-mastery-totem-v2.webp',
  ],
  [
    'beast-skill-concentration',
    '/assets/icons/beast-skill-concentration-totem-v2.webp',
  ],
  ['beast-skill-denial', '/assets/icons/beast-skill-denial-totem-v2.webp'],
  ['beast-skill-wildfire', '/assets/icons/beast-skill-wildfire-totem-v2.webp'],
  [
    'beast-skill-meditation',
    '/assets/icons/beast-skill-meditation-totem-v2.webp',
  ],
  [
    'beast-skill-sneak-attack',
    '/assets/icons/beast-skill-sneak-attack-totem-v2.webp',
  ],
  ['beast-skill-parry', '/assets/icons/beast-skill-parry-totem-v2.webp'],

  [
    'beast-skill-mountain-breaker',
    '/assets/icons/beast-skill-mountain-breaker-totem-v2.webp',
  ],
  [
    'beast-skill-karmic-retribution',
    '/assets/icons/beast-skill-karmic-retribution-totem-v2.webp',
  ],
  ['beast-skill-combo', '/assets/icons/beast-skill-combo-totem-v2.webp'],
  ['beast-skill-counter', '/assets/icons/beast-skill-counter-totem-v2.webp'],
  ['beast-skill-critical', '/assets/icons/beast-skill-critical-totem-v2.webp'],
  [
    'beast-skill-lifesteal',
    '/assets/icons/beast-skill-lifesteal-totem-v2.webp',
  ],
  [
    'beast-skill-reflection',
    '/assets/icons/beast-skill-reflection-totem-v2.webp',
  ],
  ['beast-skill-defense', '/assets/icons/beast-skill-defense-totem-v2.webp'],
  ['beast-skill-agility', '/assets/icons/beast-skill-agility-totem-v2.webp'],
  ['beast-skill-sluggish', '/assets/icons/beast-skill-sluggish-totem-v2.webp'],
  [
    'beast-skill-regeneration',
    '/assets/icons/beast-skill-regeneration-totem-v2.webp',
  ],
  ['beast-skill-ghost', '/assets/icons/beast-skill-ghost-totem-v2.webp'],
  ['beast-skill-eternity', '/assets/icons/beast-skill-eternity-totem-v2.webp'],
  [
    'beast-skill-water-attack',
    '/assets/icons/beast-skill-water-attack-totem-v2.webp',
  ],
  [
    'beast-skill-spell-critical',
    '/assets/icons/beast-skill-spell-critical-totem-v2.webp',
  ],
  [
    'beast-skill-spell-fluctuation',
    '/assets/icons/beast-skill-spell-fluctuation-totem-v2.webp',
  ],

  ['cultivator-male-avatar', '/assets/icons/cultivator-male-avatar.png'],
  ['cultivator-female-avatar', '/assets/icons/cultivator-female-avatar.png'],
  ['beast-spirit-fox', '/assets/icons/beast-spirit-fox.webp'],
  ['beast-rock-boar', '/assets/icons/beast-rock-boar.webp'],
  ['beast-wind-wolf', '/assets/icons/beast-wind-wolf.webp'],
  ['beast-red-tail-scorpion', '/assets/icons/beast-red-tail-scorpion.webp'],
  ['beast-stoneback-bear', '/assets/icons/beast-stoneback-bear.webp'],
  ['beast-mingshe', '/assets/icons/beast-mingshe.webp'],
  ['beast-shen-clam', '/assets/icons/beast-shen-clam.webp'],
  ['beast-qingluan', '/assets/icons/beast-qingluan.webp'],
  ['beast-xiezhi', '/assets/icons/beast-xiezhi.webp'],
  ['beast-nine-tailed-fox', '/assets/icons/beast-nine-tailed-fox.webp'],
  ['beast-huodou', '/assets/icons/beast-huodou.webp'],
  ['beast-xuangui', '/assets/icons/beast-xuangui.webp'],
  ['beast-zhuyan', '/assets/icons/beast-zhuyan.webp'],
  ['beast-bifang', '/assets/icons/beast-bifang.webp'],
  ['beast-baize', '/assets/icons/beast-baize.webp'],
  ['beast-qiongqi', '/assets/icons/beast-qiongqi.webp'],
  ['beast-taotie', '/assets/icons/beast-taotie.webp'],
  ['beast-yinglong', '/assets/icons/beast-yinglong.webp'],
  ['beast-golden-crow', '/assets/icons/beast-golden-crow.webp'],
  ['beast-qilin', '/assets/icons/beast-qilin.webp'],
  ['beast-diting', '/assets/icons/beast-diting.webp'],
  ['beast-fire-crow', '/assets/icons/beast-fire-crow.webp'],
  ['beast-mimi', '/assets/icons/beast-mimi.webp'],
  ['beast-nether-tiger', '/assets/icons/beast-nether-tiger.webp'],
  [
    'beast-lantern-butterfly',
    '/assets/icons/beast-ghost-lantern-butterfly.webp',
  ],
  ['beast-ink-jiao', '/assets/icons/beast-ink-jiao.webp'],
  ['beast-moon-marten', '/assets/icons/beast-moon-marten.webp'],
  ['beast-silverwing-mantis', '/assets/icons/beast-silverwing-mantis.webp'],
  ['beast-six-eyed-ape', '/assets/icons/beast-six-eyed-ape.webp'],
  ['beast-snow-crane', '/assets/icons/beast-snow-crane.webp'],
  ['beast-thunder-peng', '/assets/icons/beast-thunder-peng.webp'],
  ['beast-zheng', '/assets/icons/beast-zheng.webp'],
  ['beast-snake-neck-turtle', '/assets/icons/beast-snake-neck-turtle.webp'],
  ['beast-golden-toad', '/assets/icons/beast-three-legged-golden-toad.webp'],
]);
